### ISSUE TITLE
WebSocket Connection Not Sending Variables on Connect

### ISSUE THREAD

**Issue by ErrorGamer2000** [TurboWarp/cloud-server#65] opened 2021-07-25 21:47 UTC
I am working on a cloud api for scratch (https://github.com/ErrorGamer2000/scratch3-api). When I connect to a project on scratch, the most recent values of all of the cloud variables is sent. When connecting to turbowarp, this does not happen. After some experimentation, I found what is happening. When I load the project on tw for the first time, the current values of the cloud variables are loaded from the project's history (to be expected, as this happens when you download a project and re-upload it). The issue, though, is that tw does not count this update as a `set` action, so the server does not see that they have ever been set. So, after I changed a cloud variable in the project I now receive a `set` message as soon as I connect. This is a small bug, but would you consider making the initial load of a project act as if a user has set the cloud variables when they are first loaded?

**Comment by GarboMuffin** [comment] 2021-08-14 18:19
The problem is that when the first connection to a project is received and an internal room is created but the server is never told what variables exist until something changes

**Comment by GarboMuffin** [comment] 2022-06-16 01:05
This won't be fixed

**Closed by GarboMuffin** 2022-06-16 01:05 UTC
Labels: bug, enhancement
